### ISSUE TITLE
水平方向に移動する物体

### ISSUE THREAD

**Issue by botamochi0x12** [RubyCamp/rc2022su_team2#3]
水平方向に移動する物体を追加したい

**Comment by botamochi0x12** [comment]
`Bomb` で定義されている振る舞い (#4) を `Bomb#move` の中の `if` 文ではなく `Bomb` 系統の継承を使って実装してほしい

**Comment by botamochi0x12** [comment]
> `Bomb` で定義されている振る舞い (#4) を `Bomb#move` の中の `if` 文ではなく `Bomb` 系統の継承を使って実装してほしい

どのような `Vector3`  を渡すかによって分岐するようになった

**Comment by botamochi0x12** [comment]
使い方のデモを作る。要件は以下の通り：

- `ruby main.rb` で実行されるものと別の方法で実行される ⇐ `ruby demos.rb` のような呼び出し方で実行される 
- `game.rb` を書き換えない

**Comment by ootoro29** [comment]
#18 実装しました。
